/**
 * Structured data, generated from the price list — never hand-kept in sync.
 *
 * Everything a search engine or AI crawler reads about KENZ KLEAN (who, where, hours, contact,
 * prices, the FAQ) is built here from window.KK — the same SERVICES/EXTRAS array data.js exposes
 * and the package cards render from. Change a price in data.js and this JSON-LD changes with it on
 * the next load, so Google's rich result and the schema an AI trains on can't quote a stale figure.
 *
 * It is injected rather than written into the HTML because a static file would have to be
 * regenerated by hand every price change — the one thing this is meant to prevent. Google renders
 * JavaScript before reading structured data; the visible package prices (also from data.js) cover
 * any crawler that does not.
 *
 * The non-price facts — address, coordinates, opening hours, socials — are constants below.
 */
(() => {

const KK = window.KK;
if (!KK) return;

const SITE = "https://www.kenzklean.com.au";
const { SERVICES, EXTRAS } = KK;

const prices = SERVICES.map((s) => s.price);
const priceRange = `$${Math.min(...prices)}–$${Math.max(...prices)} AUD`;

/** "A Basic Clean is $55, Deep Clean $75, ... Extras like sole protection ($40) ...". */
const pricingSentence = () => {
  const pkgs = SERVICES.map((s) => `${s.name} $${s.price}`).join(", ").replace(/, ([^,]*)$/, " and $1");
  const extras = EXTRAS.map((e) => `${e.name.toLowerCase()} ($${e.price})`).join(", ");
  return `${pkgs} — all per pair and GST inclusive. Extras like ${extras} can be added to any clean.`;
};

const business = {
  "@type": ["LocalBusiness", "HomeAndConstructionBusiness"],
  "@id": `${SITE}/#business`,
  name: "KENZ KLEAN",
  alternateName: "KENZ KLEAN Sneaker Cleaning",
  description:
    "KENZ KLEAN is a professional sneaker cleaning and restoration service in Melbourne, Australia. Shoes are cleaned with eco-friendly, baby-safe products, photographed before and after, guaranteed against damage, and returned free to your door. Drop-off locations across Melbourne's west, plus online booking.",
  slogan: "The Most Convenient Sneaker Cleaning in Melbourne",
  url: `${SITE}/`,
  logo: `${SITE}/img/logo-96.png`,
  image: `${SITE}/img/after-1440.avif`,
  telephone: "+61482676789",
  email: "support@kenzklean.com.au",
  priceRange,
  currenciesAccepted: "AUD",
  paymentAccepted: "Cash, Card",
  knowsLanguage: "en-AU",
  address: {
    "@type": "PostalAddress",
    streetAddress: "163 Barkly St (inside Kenzo Barber Crew)",
    addressLocality: "Footscray",
    addressRegion: "VIC",
    postalCode: "3011",
    addressCountry: "AU",
  },
  geo: { "@type": "GeoCoordinates", latitude: -37.799847, longitude: 144.898939 },
  hasMap: "https://www.google.com/maps/search/?api=1&query=163%20Barkly%20St%2C%20Footscray%20VIC%203011",
  areaServed: [
    { "@type": "City", name: "Melbourne" },
    { "@type": "AdministrativeArea", name: "Greater Melbourne, Victoria, Australia" },
  ],
  openingHoursSpecification: [
    { "@type": "OpeningHoursSpecification", dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday"], opens: "10:00", closes: "18:00" },
    { "@type": "OpeningHoursSpecification", dayOfWeek: ["Friday", "Saturday"], opens: "09:00", closes: "19:00" },
    { "@type": "OpeningHoursSpecification", dayOfWeek: "Sunday", opens: "09:00", closes: "17:00" },
  ],
  sameAs: [
    "https://instagram.com/kenzklean",
    "https://youtube.com/@kenzklean",
    "https://tiktok.com/@kenzklean",
    "https://facebook.com/kenzklean",
    "https://kenzklean.square.site/",
  ],
  knowsAbout: [
    "sneaker cleaning",
    "shoe cleaning",
    "sneaker restoration",
    "sneaker repainting",
    "yellow sole whitening",
    "sole reglue",
    "leather, suede, nubuck, mesh and canvas care",
  ],
  makesOffer: SERVICES.map((s) => ({
    "@type": "Offer",
    priceCurrency: "AUD",
    price: String(s.price),
    itemOffered: {
      "@type": "Service",
      name: s.name,
      description: `${s.summary} Includes: ${s.includes.join(", ")}. Per pair, GST included.`,
    },
  })),
  hasOfferCatalog: {
    "@type": "OfferCatalog",
    name: "Sneaker cleaning packages and extras",
    itemListElement: EXTRAS.map((e) => ({
      "@type": "Offer",
      price: String(e.price),
      priceCurrency: "AUD",
      itemOffered: { "@type": "Service", name: `${e.name} (extra)` },
    })),
  },
};

const website = {
  "@type": "WebSite",
  "@id": `${SITE}/#website`,
  url: `${SITE}/`,
  name: "KENZ KLEAN",
  publisher: { "@id": `${SITE}/#business` },
  inLanguage: "en-AU",
};

const service = {
  "@type": "Service",
  serviceType: "Sneaker cleaning and restoration",
  provider: { "@id": `${SITE}/#business` },
  areaServed: { "@type": "City", name: "Melbourne" },
  description:
    "Every pair is cleaned to the material — leather, mesh, suede, nubuck and canvas each get a matched treatment — with eco-friendly, baby-safe products. Each order is photographed on intake and on completion, handled with care, and covered by a damage guarantee: if we damage your sneakers, we make it right.",
  hasOfferCatalog: { "@id": `${SITE}/#business` },
};

const q = (name, text) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } });

const faq = {
  "@type": "FAQPage",
  "@id": `${SITE}/#faq`,
  mainEntity: [
    q("Where can I get my sneakers cleaned in Melbourne?", "KENZ KLEAN cleans and restores sneakers in Melbourne. Drop your shoes at any drop-off location — the main store at 163 Barkly St, Footscray, plus partner spots in Sunshine West and St Albans — or book online and we return them free to your door in 3–5 business days."),
    q("How much does sneaker cleaning cost?", `A ${pricingSentence()}`),
    q("Do you guarantee my shoes won't be damaged?", "Yes. Every pair is cleaned to the material with eco-friendly, baby-safe products, photographed before and after so the condition is documented, and covered by a damage guarantee — if we damage your sneakers, we make it right."),
    q("What products do you clean sneakers with?", "Eco-friendly, baby-safe products. Each material — leather, mesh, suede, nubuck, canvas — gets a treatment matched to it, so nothing is stripped or discoloured."),
    q("How long does sneaker cleaning take?", "Standard turnaround is 3–5 business days with free return delivery. Express is 2–3 business days for $10 per pair, and a 24-hour turnaround is $20 per pair (drop-off and pick-up at the Footscray main store)."),
    q("Do I have to book online first?", "No. Turn up at any drop-off spot and scan the QR code on the box to register your shoes and pick a service. Booking online just means your order is waiting when you arrive and creates an account so you can track it."),
    q("Are the prices GST inclusive?", "Yes. Every price shown includes GST, so the total you see is the total you pay. Nothing is added at checkout."),
  ],
};

const graph = { "@context": "https://schema.org", "@graph": [business, website, service, faq] };

const script = document.createElement("script");
script.type = "application/ld+json";
script.textContent = JSON.stringify(graph);
document.head.appendChild(script);

})();
